// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqeasweejwfvgynrwnlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZWFzd2Vlandmdmd5bnJ3bmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MjcyMzMsImV4cCI6MjA4NTUwMzIzM30.B-QLVKBLHHBOSyGF8NXxjqJ7okaAAjMqnBF1HO2yHd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
